#
# This file contains functions that build a bayesian net and its junction tree
# Each function returns a tuple (BayesianNet, JunctionTree)
#
from bayes_nets import *

def build_studfarm():
    A = Variable('A', 'Ann', ['Carrier', 'Pure'])
    B = Variable('B', 'Brian', ['Carrier', 'Pure'])
    C = Variable('C', 'Cecily', ['Carrier', 'Pure'])
    D = Variable('D', 'Dorothy', ['Carrier', 'Pure'])
    E = Variable('E', 'Eric', ['Carrier', 'Pure'])
    F = Variable('F', 'Fred', ['Carrier', 'Pure'])
    G = Variable('G', 'Gwenn', ['Carrier', 'Pure'])
    H = Variable('H', 'Henry', ['Carrier', 'Pure'])
    I = Variable('I', 'Irene', ['Carrier', 'Pure'])
    J = Variable('J', 'John', ['Sick', 'Carrier', 'Pure'])
    K = Variable('K', 'Kafka', ['Carrier', 'Pure'])
    L = Variable('L', 'Ludwig', ['Carrier', 'Pure'])

    tA = BeliefTable([A])
    tB = BeliefTable([B])
    tC = BeliefTable([C])
    tK = BeliefTable([K])
    tL = BeliefTable([L])

    tD = BeliefTable([D, A, B])
    tE = BeliefTable([E, C, B])
    tF = BeliefTable([F, A, L])
    tG = BeliefTable([G, A, K])
    tH = BeliefTable([H, F, D])
    tI = BeliefTable([I, E, G])
    tJ = BeliefTable([J, H, I])

    # Fill tables
    tA.set_probability_dict({'A': 'Carrier'}, 0.01)
    tA.set_probability_dict({'A': 'Pure'}, 0.99)

    tB.set_probability_dict({'B': 'Carrier'}, 0.01)
    tB.set_probability_dict({'B': 'Pure'}, 0.99)

    tC.set_probability_dict({'C': 'Carrier'}, 0.01)
    tC.set_probability_dict({'C': 'Pure'}, 0.99)

    tL.set_probability_dict({'L': 'Carrier'}, 0.01)
    tL.set_probability_dict({'L': 'Pure'}, 0.99)

    tK.set_probability_dict({'K': 'Carrier'}, 0.01)
    tK.set_probability_dict({'K': 'Pure'}, 0.99)

    tF.set_probability_dict({'L': 'Carrier', 'A': 'Carrier', 'F': 'Carrier'}, 0.666667)
    tF.set_probability_dict({'L': 'Carrier', 'A': 'Carrier', 'F': 'Pure'}, 0.333333)
    tF.set_probability_dict({'L': 'Carrier', 'A': 'Pure', 'F': 'Carrier'}, 0.5)
    tF.set_probability_dict({'L': 'Carrier', 'A': 'Pure', 'F': 'Pure'}, 0.5)
    tF.set_probability_dict({'L': 'Pure', 'A': 'Carrier', 'F': 'Carrier'}, 0.5)
    tF.set_probability_dict({'L': 'Pure', 'A': 'Carrier', 'F': 'Pure'}, 0.5)
    tF.set_probability_dict({'L': 'Pure', 'A': 'Pure', 'F': 'Carrier'}, 0)
    tF.set_probability_dict({'L': 'Pure', 'A': 'Pure', 'F': 'Pure'}, 1)

    tD.set_probability_dict({'A': 'Carrier', 'B': 'Carrier', 'D': 'Carrier'}, 0.666667)
    tD.set_probability_dict({'A': 'Carrier', 'B': 'Carrier', 'D': 'Pure'}, 0.333333)
    tD.set_probability_dict({'A': 'Carrier', 'B': 'Pure', 'D': 'Carrier'}, 0.5)
    tD.set_probability_dict({'A': 'Carrier', 'B': 'Pure', 'D': 'Pure'}, 0.5)
    tD.set_probability_dict({'A': 'Pure', 'B': 'Carrier', 'D': 'Carrier'}, 0.5)
    tD.set_probability_dict({'A': 'Pure', 'B': 'Carrier', 'D': 'Pure'}, 0.5)
    tD.set_probability_dict({'A': 'Pure', 'B': 'Pure', 'D': 'Carrier'}, 0)
    tD.set_probability_dict({'A': 'Pure', 'B': 'Pure', 'D': 'Pure'}, 1)

    tE.set_probability_dict({'B': 'Carrier', 'C': 'Carrier', 'E': 'Carrier'}, 0.666667)
    tE.set_probability_dict({'B': 'Carrier', 'C': 'Carrier', 'E': 'Pure'}, 0.333333)
    tE.set_probability_dict({'B': 'Carrier', 'C': 'Pure', 'E': 'Carrier'}, 0.5)
    tE.set_probability_dict({'B': 'Carrier', 'C': 'Pure', 'E': 'Pure'}, 0.5)
    tE.set_probability_dict({'B': 'Pure', 'C': 'Carrier', 'E': 'Carrier'}, 0.5)
    tE.set_probability_dict({'B': 'Pure', 'C': 'Carrier', 'E': 'Pure'}, 0.5)
    tE.set_probability_dict({'B': 'Pure', 'C': 'Pure', 'E': 'Carrier'}, 0)
    tE.set_probability_dict({'B': 'Pure', 'C': 'Pure', 'E': 'Pure'}, 1)

    tG.set_probability_dict({'A': 'Carrier', 'K': 'Carrier', 'G': 'Carrier'}, 0.666667)
    tG.set_probability_dict({'A': 'Carrier', 'K': 'Carrier', 'G': 'Pure'}, 0.333333)
    tG.set_probability_dict({'A': 'Carrier', 'K': 'Pure', 'G': 'Carrier'}, 0.5)
    tG.set_probability_dict({'A': 'Carrier', 'K': 'Pure', 'G': 'Pure'}, 0.5)
    tG.set_probability_dict({'A': 'Pure', 'K': 'Carrier', 'G': 'Carrier'}, 0.5)
    tG.set_probability_dict({'A': 'Pure', 'K': 'Carrier', 'G': 'Pure'}, 0.5)
    tG.set_probability_dict({'A': 'Pure', 'K': 'Pure', 'G': 'Carrier'}, 0)
    tG.set_probability_dict({'A': 'Pure', 'K': 'Pure', 'G': 'Pure'}, 1)

    tH.set_probability_dict({'F': 'Carrier', 'D': 'Carrier', 'H': 'Carrier'}, 0.666667)
    tH.set_probability_dict({'F': 'Carrier', 'D': 'Carrier', 'H': 'Pure'}, 0.333333)
    tH.set_probability_dict({'F': 'Carrier', 'D': 'Pure', 'H': 'Carrier'}, 0.5)
    tH.set_probability_dict({'F': 'Carrier', 'D': 'Pure', 'H': 'Pure'}, 0.5)
    tH.set_probability_dict({'F': 'Pure', 'D': 'Carrier', 'H': 'Carrier'}, 0.5)
    tH.set_probability_dict({'F': 'Pure', 'D': 'Carrier', 'H': 'Pure'}, 0.5)
    tH.set_probability_dict({'F': 'Pure', 'D': 'Pure', 'H': 'Carrier'}, 0)
    tH.set_probability_dict({'F': 'Pure', 'D': 'Pure', 'H': 'Pure'}, 1)

    tI.set_probability_dict({'E': 'Carrier', 'G': 'Carrier', 'I': 'Carrier'}, 0.666667)
    tI.set_probability_dict({'E': 'Carrier', 'G': 'Carrier', 'I': 'Pure'}, 0.333333)
    tI.set_probability_dict({'E': 'Carrier', 'G': 'Pure', 'I': 'Carrier'}, 0.5)
    tI.set_probability_dict({'E': 'Carrier', 'G': 'Pure', 'I': 'Pure'}, 0.5)
    tI.set_probability_dict({'E': 'Pure', 'G': 'Carrier', 'I': 'Carrier'}, 0.5)
    tI.set_probability_dict({'E': 'Pure', 'G': 'Carrier', 'I': 'Pure'}, 0.5)
    tI.set_probability_dict({'E': 'Pure', 'G': 'Pure', 'I': 'Carrier'}, 0)
    tI.set_probability_dict({'E': 'Pure', 'G': 'Pure', 'I': 'Pure'}, 1)

    tJ.set_probability_dict({'H': 'Carrier', 'I': 'Carrier', 'J': 'Sick'}, 0.25)
    tJ.set_probability_dict({'H': 'Carrier', 'I': 'Carrier', 'J': 'Carrier'}, 0.5)
    tJ.set_probability_dict({'H': 'Carrier', 'I': 'Carrier', 'J': 'Pure'}, 0.25)
    tJ.set_probability_dict({'H': 'Carrier', 'I': 'Pure', 'J': 'Sick'}, 0)
    tJ.set_probability_dict({'H': 'Carrier', 'I': 'Pure', 'J': 'Carrier'}, 0.5)
    tJ.set_probability_dict({'H': 'Carrier', 'I': 'Pure', 'J': 'Pure'}, 0.5)
    tJ.set_probability_dict({'H': 'Pure', 'I': 'Carrier', 'J': 'Sick'}, 0)
    tJ.set_probability_dict({'H': 'Pure', 'I': 'Carrier', 'J': 'Carrier'}, 0.5)
    tJ.set_probability_dict({'H': 'Pure', 'I': 'Carrier', 'J': 'Pure'}, 0.5)
    tJ.set_probability_dict({'H': 'Pure', 'I': 'Pure', 'J': 'Sick'}, 0)
    tJ.set_probability_dict({'H': 'Pure', 'I': 'Pure', 'J': 'Carrier'}, 0)
    tJ.set_probability_dict({'H': 'Pure', 'I': 'Pure', 'J': 'Pure'}, 1)

    net = BayesianNet()
    net.add_variable(A)
    net.add_variable(B)
    net.add_variable(C)
    net.add_variable(D)
    net.add_variable(E)
    net.add_variable(F)
    net.add_variable(G)
    net.add_variable(H)
    net.add_variable(I)
    net.add_variable(J)
    net.add_variable(K)
    net.add_variable(L)

    net.add_dependence(F, L)
    net.add_dependence(F, A)
    net.add_dependence(D, A)
    net.add_dependence(D, B)
    net.add_dependence(E, B)
    net.add_dependence(E, C)
    net.add_dependence(G, A)
    net.add_dependence(G, K)
    net.add_dependence(H, F)
    net.add_dependence(H, D)
    net.add_dependence(I, E)
    net.add_dependence(I, G)
    net.add_dependence(J, H)
    net.add_dependence(J, I)

    net.add_prob_table(A, tA)
    net.add_prob_table(B, tB)
    net.add_prob_table(C, tC)
    net.add_prob_table(D, tD)
    net.add_prob_table(E, tE)
    net.add_prob_table(F, tF)
    net.add_prob_table(G, tG)
    net.add_prob_table(H, tH)
    net.add_prob_table(I, tI)
    net.add_prob_table(J, tJ)
    net.add_prob_table(K, tK)
    net.add_prob_table(L, tL)

    jtree = JunctionTree([A, B, C, D, E, F, G, H, I, J, K, L])

    jtree.add_clique([H, I, J])
    jtree.add_clique([A, H, B, I])
    jtree.add_clique([A, B, I, G])
    jtree.add_clique([A, G, K])
    jtree.add_clique([B, I, G, E])
    jtree.add_clique([B, E, C])
    jtree.add_clique([A, H, D, B])
    jtree.add_clique([A, F, H, D])
    jtree.add_clique([A, F, L])

    jtree.connect_cliques([H, I, J], [A, H, B, I])
    jtree.connect_cliques([A, H, B, I], [A, G, B, I])
    jtree.connect_cliques([A, G, B, I], [A, G, K])
    jtree.connect_cliques([A, G, B, I], [B, I, G, E])
    jtree.connect_cliques([B, I, G, E], [B, E, C])
    jtree.connect_cliques([A, H, B, I], [A, H, D, B])
    jtree.connect_cliques([A, H, D, B], [A, F, H, D])
    jtree.connect_cliques([A, F, H, D], [A, F, L])

    return net, jtree





def build_cancer():
    MC = Variable('MC', 'Metastatic Cancer', ['Present', 'Absent'])
    S = Variable('S', 'Serum Calcium', ['Increased', 'Not increased'])
    T = Variable('T', 'Brain Tumor', ['Present', 'Absent'])
    C = Variable('C', 'Coma', ['Present', 'Absent'])
    H = Variable('H', 'Severe Headaches', ['Present', 'Absent'])

    tMC = BeliefTable([MC])
    tS = BeliefTable([S, MC])
    tT = BeliefTable([T, MC])
    tC = BeliefTable([C, S, T])
    tH = BeliefTable([H, T])

    tMC.set_probability_dict({'MC': 'Absent'}, 0.8)
    tMC.set_probability_dict({'MC': 'Present'}, 0.2)

    tS.set_probability_dict({'S': 'Not increased', 'MC': 'Absent'}, 0.8)
    tS.set_probability_dict({'S': 'Not increased', 'MC': 'Present'}, 0.2)
    tS.set_probability_dict({'S': 'Increased', 'MC': 'Absent'}, 0.2)
    tS.set_probability_dict({'S': 'Increased', 'MC': 'Present'}, 0.8)

    tT.set_probability_dict({'T': 'Absent', 'MC': 'Absent'}, 0.95)
    tT.set_probability_dict({'T': 'Absent', 'MC': 'Present'}, 0.8)
    tT.set_probability_dict({'T': 'Present', 'MC': 'Absent'}, 0.05)
    tT.set_probability_dict({'T': 'Present', 'MC': 'Present'}, 0.2)

    tC.set_probability_dict({'C': 'Absent', 'S': 'Not increased', 'T': 'Absent'}, 0.95)
    tC.set_probability_dict({'C': 'Absent', 'S': 'Not increased', 'T': 'Present'}, 0.2)
    tC.set_probability_dict({'C': 'Absent', 'S': 'Increased', 'T': 'Absent'}, 0.2)
    tC.set_probability_dict({'C': 'Absent', 'S': 'Increased', 'T': 'Present'}, 0.2)
    tC.set_probability_dict({'C': 'Present', 'S': 'Not increased', 'T': 'Absent'}, 0.05)
    tC.set_probability_dict({'C': 'Present', 'S': 'Not increased', 'T': 'Present'}, 0.8)
    tC.set_probability_dict({'C': 'Present', 'S': 'Increased', 'T': 'Absent'}, 0.8)
    tC.set_probability_dict({'C': 'Present', 'S': 'Increased', 'T': 'Present'}, 0.8)

    tH.set_probability_dict({'H': 'Absent', 'T': 'Absent'}, 0.4)
    tH.set_probability_dict({'H': 'Absent', 'T': 'Present'}, 0.2)
    tH.set_probability_dict({'H': 'Present', 'T': 'Absent'}, 0.6)
    tH.set_probability_dict({'H': 'Present', 'T': 'Present'}, 0.8)

    net = BayesianNet()
    net.add_variable(MC)
    net.add_variable(S)
    net.add_variable(T)
    net.add_variable(C)
    net.add_variable(H)

    net.add_dependence('S', 'MC')
    net.add_dependence('T', 'MC')
    net.add_dependence('C', 'S')
    net.add_dependence('C', 'T')
    net.add_dependence('H', 'T')

    net.add_prob_table('MC', tMC)
    net.add_prob_table('S', tS)
    net.add_prob_table('T', tT)
    net.add_prob_table('C', tC)
    net.add_prob_table('H', tH)

    jtree = JunctionTree([MC, S, T, C, H])

    jtree.add_clique(['T', 'S', 'C'])
    jtree.add_clique(['T', 'S', 'MC'])
    jtree.add_clique(['T', 'H'])

    jtree.connect_cliques(['T', 'S', 'MC'], ['T', 'S', 'C'])
    jtree.connect_cliques(['T', 'S', 'MC'], ['T', 'H'])

    return net, jtree

def build_fire():
    S = Variable('S', 'Smoke', ['true', 'false'])
    F = Variable('F', 'Fire', ['true', 'false'])
    A = Variable('A', 'Alarm', ['true', 'false'])
    T = Variable('T', 'Tampering', ['true', 'false'])
    L = Variable('L', 'Leaving', ['true', 'false'])
    R = Variable('R', 'Report', ['true', 'false'])

    tS = BeliefTable([S, F])
    tF = BeliefTable([F])
    tA = BeliefTable([A, F, T])
    tT = BeliefTable([T])
    tL = BeliefTable([A, L])
    tR = BeliefTable([R, L])

    # Fill tables
    tS.set_probability_dict({'F': 'true', 'S': 'true'}, 0.9)
    tS.set_probability_dict({'F': 'true', 'S': 'false'}, 0.1)
    tS.set_probability_dict({'F': 'false', 'S': 'true'}, 0.01)
    tS.set_probability_dict({'F': 'false', 'S': 'false'}, 0.99)

    tF.set_probability_dict({'F': 'true'}, 0.01)
    tF.set_probability_dict({'F': 'false'}, 0.99)

    tA.set_probability_dict({'F': 'true', 'T': 'true', 'A': 'true'}, 0.5)
    tA.set_probability_dict({'F': 'true', 'T': 'true', 'A': 'false'}, 0.5)
    tA.set_probability_dict({'F': 'true', 'T': 'false', 'A': 'true'}, 0.99)
    tA.set_probability_dict({'F': 'true', 'T': 'false', 'A': 'false'}, 0.01)
    tA.set_probability_dict({'F': 'false', 'T': 'true', 'A': 'true'}, 0.85)
    tA.set_probability_dict({'F': 'false', 'T': 'true', 'A': 'false'}, 0.15)
    tA.set_probability_dict({'F': 'false', 'T': 'false', 'A': 'true'}, 0.0001)
    tA.set_probability_dict({'F': 'false', 'T': 'false', 'A': 'false'}, 0.9999)

    tT.set_probability_dict({'T': 'true'}, 0.02)
    tT.set_probability_dict({'T': 'false'}, 0.98)

    tL.set_probability_dict({'A': 'true', 'L': 'true'}, 0.88)
    tL.set_probability_dict({'A': 'true', 'L': 'false'}, 0.12)
    tL.set_probability_dict({'A': 'false', 'L': 'true'}, 0.001)
    tL.set_probability_dict({'A': 'false', 'L': 'false'}, 0.999)

    tR.set_probability_dict({'L': 'true', 'R': 'true'}, 0.75)
    tR.set_probability_dict({'L': 'true', 'R': 'false'}, 0.25)
    tR.set_probability_dict({'L': 'false', 'R': 'true'}, 0.01)
    tR.set_probability_dict({'L': 'false', 'R': 'false'}, 0.99)

    net = BayesianNet()

    net.add_variable(S)
    net.add_variable(F)
    net.add_variable(A)
    net.add_variable(T)
    net.add_variable(L)
    net.add_variable(R)

    net.add_dependence(S, F)
    net.add_dependence(A, F)
    net.add_dependence(A, T)
    net.add_dependence(L, A)
    net.add_dependence(R, L)

    net.add_prob_table(S, tS)
    net.add_prob_table(F, tF)
    net.add_prob_table(A, tA)
    net.add_prob_table(T, tT)
    net.add_prob_table(L, tL)
    net.add_prob_table(R, tR)

    jtree = JunctionTree([S, F, A, T, L, R])

    jtree.add_clique([F, S])
    jtree.add_clique([A, F, T])
    jtree.add_clique([L, A])
    jtree.add_clique([L, R])

    jtree.connect_cliques([F, S], [A, F, T])
    jtree.connect_cliques([A, F, T], [L, A])
    jtree.connect_cliques([L, A], [L, R])

    return net, jtree


def build_poker():
    possible_hands = ['no', '1 ace', '2 consecutive', '2 of a suit', '2 alike', 'flush', 'straight', '3 alike',
                      'straight flush']
    OH0 = Variable('OH0', 'Opponent\'s initial hand', possible_hands)
    OH1 = Variable('OH1', 'Opponent\'s hand after one round of discarding', possible_hands)
    OH2 = Variable('OH2', 'Opponent\'s hand after 2 rounds of discarding',
                   ['no', '1 ace', '2 consecutive', '2 alike', 'flush', 'straight', '3 alike',
                    'straight flush']
                   )
    FC = Variable('FC', 'Number of cards discarded by opp during first round of discarding',
                  ['0 changed', '1 changed', '2 changed', '3 changed'])
    SC = Variable('SC', 'Number of cards discarded by opp during second round of discarding',
                  ['0 changed', '1 changed', '2 changed'])
    MH = Variable('MH', 'My hand', ['no', '1 ace', '2 consecutive', '2 alike', 'flush', 'straight', '3 alike',
                      'straight flush'])
    BH = Variable('BH', 'Who has the best hand', ['myhand', 'opponent'])

    tOH0 = BeliefTable([OH0])
    tOH1 = BeliefTable([OH0, FC, OH1])
    tFC = BeliefTable([OH0, FC])
    tOH2 = BeliefTable([OH1, SC, OH2])
    tSC = BeliefTable([OH1, SC])
    tMH = BeliefTable([MH])
    tBH = BeliefTable([MH, OH2, BH])

    # Fill tables(good luck)
    tMH.set_probability_dict({'MH': slice(None)}, (0.125, 0.125, 0.125 ,0.125, 0.125, 0.125, 0.125, 0.125))

    tOH0.set_probability_dict({'OH0': slice(None)},
                              (0.1672, 0.0445, 0.0635, 0.4659, 0.1694, 0.0494, 0.0353, 0.0024, 0.0024))

    tFC.set_probability_dict({'OH0': 'no', 'FC': slice(None)}, (0, 0, 0, 1))
    tFC.set_probability_dict({'OH0': '1 ace', 'FC': slice(None)}, (0, 0, 1, 0) )
    tFC.set_probability_dict({'OH0': '2 consecutive', 'FC': slice(None)}, (0, 1, 0, 0))
    tFC.set_probability_dict({'OH0': '2 of a suit', 'FC': slice(None)}, (0, 1, 0, 0))
    tFC.set_probability_dict({'OH0': '2 alike', 'FC': slice(None)}, (0, 1, 0, 0))
    tFC.set_probability_dict({'OH0': 'flush', 'FC': slice(None)}, (1, 0, 0, 0))
    tFC.set_probability_dict({'OH0': 'straight', 'FC': slice(None)}, (1, 0, 0, 0))
    tFC.set_probability_dict({'OH0': '3 alike', 'FC': slice(None)}, (1, 0, 0, 0))
    tFC.set_probability_dict({'OH0': 'straight flush', 'FC': slice(None)}, (1, 0, 0, 0))

    tSC.set_probability_dict({'OH1': 'no', 'SC': slice(None)}, (0, 0, 1))
    tSC.set_probability_dict({'OH1': '1 ace', 'SC': slice(None)}, (0, 0, 1) )
    tSC.set_probability_dict({'OH1': '2 consecutive', 'SC': slice(None)}, (0, 1, 0))
    tSC.set_probability_dict({'OH1': '2 of a suit', 'SC': slice(None)}, (0, 1, 0))
    tSC.set_probability_dict({'OH1': '2 alike', 'SC': slice(None)}, (0, 1, 0))
    tSC.set_probability_dict({'OH1': 'flush', 'SC': slice(None)}, (1, 0, 0))
    tSC.set_probability_dict({'OH1': 'straight', 'SC': slice(None)}, (1, 0, 0))
    tSC.set_probability_dict({'OH1': '3 alike', 'SC': slice(None)}, (1, 0, 0))
    tSC.set_probability_dict({'OH1': 'straight flush', 'SC': slice(None)}, (1, 0, 0))

    tBH.set_probability_dict({'MH': 'no', 'OH2': 'no', 'BH': slice(None)}, (0.5,0.5))
    tBH.set_probability_dict({'MH': 'no', 'OH2': '1 ace', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'no', 'OH2': '2 consecutive', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'no', 'OH2': '2 alike', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'no', 'OH2': 'flush', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'no', 'OH2': 'straight', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'no', 'OH2': '3 alike', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'no', 'OH2': 'straight flush', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '1 ace', 'OH2': 'no', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '1 ace', 'OH2': '1 ace', 'BH': slice(None)}, (0.5,0.5))
    tBH.set_probability_dict({'MH': '1 ace', 'OH2': '2 consecutive', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '1 ace', 'OH2': '2 alike', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '1 ace', 'OH2': 'flush', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '1 ace', 'OH2': 'straight', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '1 ace', 'OH2': '3 alike', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '1 ace', 'OH2': 'straight flush', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '2 consecutive', 'OH2': 'no', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '2 consecutive', 'OH2': '1 ace', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '2 consecutive', 'OH2': '2 consecutive', 'BH': slice(None)}, (0.5,0.5))
    tBH.set_probability_dict({'MH': '2 consecutive', 'OH2': '2 alike', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '2 consecutive', 'OH2': 'flush', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '2 consecutive', 'OH2': 'straight', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '2 consecutive', 'OH2': '3 alike', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '2 consecutive', 'OH2': 'straight flush', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '2 alike', 'OH2': 'no', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '2 alike', 'OH2': '1 ace', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '2 alike', 'OH2': '2 consecutive', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '2 alike', 'OH2': '2 alike', 'BH': slice(None)}, (0.5,0.5))
    tBH.set_probability_dict({'MH': '2 alike', 'OH2': 'flush', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '2 alike', 'OH2': 'straight', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '2 alike', 'OH2': '3 alike', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '2 alike', 'OH2': 'straight flush', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'flush', 'OH2': 'no', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'flush', 'OH2': '1 ace', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'flush', 'OH2': '2 consecutive', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'flush', 'OH2': '2 alike', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'flush', 'OH2': 'flush', 'BH': slice(None)}, (0.5,0.5))
    tBH.set_probability_dict({'MH': 'flush', 'OH2': 'straight', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'flush', 'OH2': '3 alike', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'flush', 'OH2': 'straight flush', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'straight', 'OH2': 'no', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight', 'OH2': '1 ace', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight', 'OH2': '2 consecutive', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight', 'OH2': '2 alike', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight', 'OH2': 'flush', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight', 'OH2': 'straight', 'BH': slice(None)}, (0.5,0.5))
    tBH.set_probability_dict({'MH': 'straight', 'OH2': '3 alike', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'straight', 'OH2': 'straight flush', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': '3 alike', 'OH2': 'no', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '3 alike', 'OH2': '1 ace', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '3 alike', 'OH2': '2 consecutive', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '3 alike', 'OH2': '2 alike', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '3 alike', 'OH2': 'flush', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '3 alike', 'OH2': 'straight', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': '3 alike', 'OH2': '3 alike', 'BH': slice(None)}, (0.5,0.5))
    tBH.set_probability_dict({'MH': '3 alike', 'OH2': 'straight flush', 'BH': slice(None)}, (0,1))
    tBH.set_probability_dict({'MH': 'straight flush', 'OH2': 'no', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight flush', 'OH2': '1 ace', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight flush', 'OH2': '2 consecutive', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight flush', 'OH2': '2 alike', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight flush', 'OH2': 'flush', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight flush', 'OH2': 'straight', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight flush', 'OH2': '3 alike', 'BH': slice(None)}, (1,0))
    tBH.set_probability_dict({'MH': 'straight flush', 'OH2': 'straight flush', 'BH': slice(None)}, (0.5,0.5))

    tOH1.set_probability_dict({'FC': '0 changed', 'OH0': 'no', 'OH1': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '0 changed', 'OH0': '1 ace', 'OH1': slice(None)}, (0, 1, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '0 changed', 'OH0': '2 consecutive', 'OH1': slice(None)}, (0, 0, 1, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '0 changed', 'OH0': '2 of a suit', 'OH1': slice(None)}, (0, 0, 0, 1, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '0 changed', 'OH0': '2 alike', 'OH1': slice(None)}, (0, 0, 0, 0, 1, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '0 changed', 'OH0': 'flush', 'OH1': slice(None)}, (0, 0, 0, 0, 0, 1, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '0 changed', 'OH0': 'straight', 'OH1': slice(None)}, (0, 0, 0, 0, 0, 0, 1, 0, 0))
    tOH1.set_probability_dict({'FC': '0 changed', 'OH0': '3 alike', 'OH1': slice(None)}, (0, 0, 0, 0, 0, 0, 0, 1, 0))
    tOH1.set_probability_dict({'FC': '0 changed', 'OH0': 'straight flush', 'OH1': slice(None)}, (0, 0, 0, 0, 0, 0, 0, 0, 1))
    tOH1.set_probability_dict({'FC': '1 changed', 'OH0': 'no', 'OH1': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '1 changed', 'OH0': '1 ace', 'OH1': slice(None)}, (0, 1, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '1 changed', 'OH0': '2 consecutive', 'OH1': slice(None)}, (0, 0, 0.347, 0.3674, 0.1224, 0, 0.1632, 0, 0))
    tOH1.set_probability_dict({'FC': '1 changed', 'OH0': '2 of a suit', 'OH1': slice(None)}, (0, 0, 0, 0.6224, 0.1224, 0.2143, 0.0307, 0, 0.0102))
    tOH1.set_probability_dict({'FC': '1 changed', 'OH0': '2 alike', 'OH1': slice(None)}, (0, 0, 0, 0, 0.9592, 0, 0, 0.0408, 0))
    tOH1.set_probability_dict({'FC': '1 changed', 'OH0': 'flush', 'OH1': slice(None)}, (0, 0, 1, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '1 changed', 'OH0': 'straight', 'OH1': slice(None)}, (0, 0, 0, 1, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '1 changed', 'OH0': '3 alike', 'OH1': slice(None)}, (0, 0, 0, 0, 1, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '1 changed', 'OH0': 'straight flush', 'OH1': slice(None)}, (0, 0, 0, 0, 0, 0.5, 0.5, 0, 0))
    tOH1.set_probability_dict({'FC': '2 changed', 'OH0': 'no', 'OH1': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '2 changed', 'OH0': '1 ace', 'OH1': slice(None)}, (0, 0.1814, 0.0681, 0.4796, 0.1738, 0.0536, 0.0383, 0.0026, 0.0026))
    tOH1.set_probability_dict({'FC': '2 changed', 'OH0': '2 consecutive', 'OH1': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '2 changed', 'OH0': '2 of a suit', 'OH1': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '2 changed', 'OH0': '2 alike', 'OH1': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '2 changed', 'OH0': 'flush', 'OH1': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '2 changed', 'OH0': 'straight', 'OH1': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '2 changed', 'OH0': '3 alike', 'OH1': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '2 changed', 'OH0': 'straight flush', 'OH1': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '3 changed', 'OH0': 'no', 'OH1': slice(None)}, (0.1583, 0.0534, 0.0635, 0.4659, 0.1694, 0.0494, 0.0353, 0.0024, 0.0024))
    tOH1.set_probability_dict({'FC': '3 changed', 'OH0': '1 ace', 'OH1': slice(None)}, (0, 1, 0, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '3 changed', 'OH0': '2 consecutive', 'OH1': slice(None)}, (0, 0, 1, 0, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '3 changed', 'OH0': '2 of a suit', 'OH1': slice(None)}, (0, 0, 0, 1, 0, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '3 changed', 'OH0': '2 alike', 'OH1': slice(None)}, (0, 0, 0, 0, 1, 0, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '3 changed', 'OH0': 'flush', 'OH1': slice(None)}, (0, 0, 0, 0, 0, 1, 0, 0, 0))
    tOH1.set_probability_dict({'FC': '3 changed', 'OH0': 'straight', 'OH1': slice(None)}, (0, 0, 0, 0, 0, 0, 1, 0, 0))
    tOH1.set_probability_dict({'FC': '3 changed', 'OH0': '3 alike', 'OH1': slice(None)}, (0, 0, 0, 0, 0, 0, 0, 1, 0))
    tOH1.set_probability_dict({'FC': '3 changed', 'OH0': 'straight flush', 'OH1': slice(None)}, (0, 0, 0, 0, 0, 0, 0, 0, 1))

    tOH2.set_probability_dict({'SC': '0 changed', 'OH1': 'no', 'OH2': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '0 changed', 'OH1': '1 ace', 'OH2': slice(None)}, (0, 1, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '0 changed', 'OH1': '2 consecutive', 'OH2': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '0 changed', 'OH1': '2 of a suit', 'OH2': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '0 changed', 'OH1': '2 alike', 'OH2': slice(None)}, (0, 0, 0.9231, 0.0769, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '0 changed', 'OH1': 'flush', 'OH2': slice(None)}, (0, 0, 0, 0, 1, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '0 changed', 'OH1': 'straight', 'OH2': slice(None)}, (0, 0, 0, 0, 0, 1, 0, 0))
    tOH2.set_probability_dict({'SC': '0 changed', 'OH1': '3 alike', 'OH2': slice(None)}, (0, 0, 0, 0, 0, 0, 1, 0))
    tOH2.set_probability_dict({'SC': '0 changed', 'OH1': 'straight flush', 'OH2': slice(None)}, (0, 0, 0, 0, 0, 0, 0, 1))
    tOH2.set_probability_dict({'SC': '1 changed', 'OH1': 'no', 'OH2': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '1 changed', 'OH1': '1 ace', 'OH2': slice(None)}, (0, 1, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '1 changed', 'OH1': '2 consecutive', 'OH2': slice(None)}, (0.5903, 0.1181, 0.1154, 0.0096, 0, 0.1666, 0, 0))
    tOH2.set_probability_dict({'SC': '1 changed', 'OH1': '2 of a suit', 'OH2': slice(None)}, (0.5121, 0.1024, 0.1154, 0.0096, 0.2188, 0.0313, 0, 0.0104))
    tOH2.set_probability_dict({'SC': '1 changed', 'OH1': '2 alike', 'OH2': slice(None)}, (0, 0, 0.8838, 0.0736, 0, 0, 0.0426, 0))
    tOH2.set_probability_dict({'SC': '1 changed', 'OH1': 'flush', 'OH2': slice(None)}, (0, 0, 0, 0, 1, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '1 changed', 'OH1': 'straight', 'OH2': slice(None)}, (0, 0, 0, 0, 0, 1, 0, 0))
    tOH2.set_probability_dict({'SC': '1 changed', 'OH1': '3 alike', 'OH2': slice(None)}, (0, 0, 0, 0, 0, 0, 1, 0))
    tOH2.set_probability_dict({'SC': '1 changed', 'OH1': 'straight flush', 'OH2': slice(None)}, (0, 0, 0, 0, 0, 0, 0, 1))
    tOH2.set_probability_dict({'SC': '2 changed', 'OH1': 'no', 'OH2': slice(None)}, (0.5613, 0.1570, 0.1757, 0.0055, 0.0559, 0.0392, 0.0027, 0.0027))
    tOH2.set_probability_dict({'SC': '2 changed', 'OH1': '1 ace', 'OH2': slice(None)}, (0, 0.7183, 0.0667, 0.1145, 0.0559, 0.0392, 0.0027, 0.0027))
    tOH2.set_probability_dict({'SC': '2 changed', 'OH1': '2 consecutive', 'OH2': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '2 changed', 'OH1': '2 of a suit', 'OH2': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '2 changed', 'OH1': '2 alike', 'OH2': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '2 changed', 'OH1': 'flush', 'OH2': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '2 changed', 'OH1': 'straight', 'OH2': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '2 changed', 'OH1': '3 alike', 'OH2': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0))
    tOH2.set_probability_dict({'SC': '2 changed', 'OH1': 'straight flush', 'OH2': slice(None)}, (1, 0, 0, 0, 0, 0, 0, 0))

    #################
    net = BayesianNet()
    net.add_variable(OH0)
    net.add_variable(OH1)
    net.add_variable(OH2)
    net.add_variable(FC)
    net.add_variable(SC)
    net.add_variable(MH)
    net.add_variable(BH)

    net.add_dependence(FC, OH0)
    net.add_dependence(OH1, OH0)
    net.add_dependence(OH1, FC)
    net.add_dependence(SC, OH1)
    net.add_dependence(OH2, OH1)
    net.add_dependence(OH2, SC)
    net.add_dependence(BH, MH)
    net.add_dependence(BH, OH2)

    net.add_prob_table(OH0, tOH0)
    net.add_prob_table(OH1, tOH1)
    net.add_prob_table(OH2, tOH2)
    net.add_prob_table(FC, tFC)
    net.add_prob_table(SC, tSC)
    net.add_prob_table(MH, tMH)
    net.add_prob_table(BH, tBH)

    jtree = JunctionTree([OH0, OH1, OH2, FC, SC, MH, BH])

    jtree.add_clique([OH1, OH0, FC])
    jtree.add_clique([OH2, OH1, SC])
    jtree.add_clique([OH2, BH, MH])

    jtree.connect_cliques([OH1, OH0, FC], [OH1, OH2, SC])
    jtree.connect_cliques([OH1, OH2, SC], [OH2, BH, MH])

    return net, jtree



def build_monty():
    P = Variable('P', 'Prize', ['door1', 'door2', 'door3'])
    F = Variable('F', 'First Choice', ['door1', 'door2', 'door3'])
    M = Variable('M', 'Monty Opens', ['door1', 'door2', 'door3'])

    tP = BeliefTable([P])
    tF = BeliefTable([F])
    tM = BeliefTable([P, F, M])

    # Fill tables
    tP.set_probability_dict({'P': 'door1'}, 0.3333)
    tP.set_probability_dict({'P': 'door2'}, 0.3333)
    tP.set_probability_dict({'P': 'door3'}, 0.3333)

    tF.set_probability_dict({'F': 'door1'}, 0.3333)
    tF.set_probability_dict({'F': 'door2'}, 0.3333)
    tF.set_probability_dict({'F': 'door3'}, 0.3333)

    tM.set_probability_dict({'P': 'door1', 'F': 'door1', 'M': 'door1'}, 0)
    tM.set_probability_dict({'P': 'door1', 'F': 'door1', 'M': 'door2'}, 0.5)
    tM.set_probability_dict({'P': 'door1', 'F': 'door1', 'M': 'door3'}, 0.5)
    tM.set_probability_dict({'P': 'door1', 'F': 'door2', 'M': 'door1'}, 0)
    tM.set_probability_dict({'P': 'door1', 'F': 'door2', 'M': 'door2'}, 0)
    tM.set_probability_dict({'P': 'door1', 'F': 'door2', 'M': 'door3'}, 1)
    tM.set_probability_dict({'P': 'door1', 'F': 'door3', 'M': 'door1'}, 0)
    tM.set_probability_dict({'P': 'door1', 'F': 'door3', 'M': 'door2'}, 1)
    tM.set_probability_dict({'P': 'door1', 'F': 'door3', 'M': 'door3'}, 0)
    tM.set_probability_dict({'P': 'door2', 'F': 'door1', 'M': 'door1'}, 0)
    tM.set_probability_dict({'P': 'door2', 'F': 'door1', 'M': 'door2'}, 0)
    tM.set_probability_dict({'P': 'door2', 'F': 'door1', 'M': 'door3'}, 1)
    tM.set_probability_dict({'P': 'door2', 'F': 'door2', 'M': 'door1'}, 0.5)
    tM.set_probability_dict({'P': 'door2', 'F': 'door2', 'M': 'door2'}, 0)
    tM.set_probability_dict({'P': 'door2', 'F': 'door2', 'M': 'door3'}, 0.5)
    tM.set_probability_dict({'P': 'door2', 'F': 'door3', 'M': 'door1'}, 1)
    tM.set_probability_dict({'P': 'door2', 'F': 'door3', 'M': 'door2'}, 0)
    tM.set_probability_dict({'P': 'door2', 'F': 'door3', 'M': 'door3'}, 0)
    tM.set_probability_dict({'P': 'door3', 'F': 'door1', 'M': 'door1'}, 0)
    tM.set_probability_dict({'P': 'door3', 'F': 'door1', 'M': 'door2'}, 1)
    tM.set_probability_dict({'P': 'door3', 'F': 'door1', 'M': 'door3'}, 0)
    tM.set_probability_dict({'P': 'door3', 'F': 'door2', 'M': 'door1'}, 1)
    tM.set_probability_dict({'P': 'door3', 'F': 'door2', 'M': 'door2'}, 0)
    tM.set_probability_dict({'P': 'door3', 'F': 'door2', 'M': 'door3'}, 0)
    tM.set_probability_dict({'P': 'door3', 'F': 'door3', 'M': 'door1'}, 0.5)
    tM.set_probability_dict({'P': 'door3', 'F': 'door3', 'M': 'door2'}, 0.5)
    tM.set_probability_dict({'P': 'door3', 'F': 'door3', 'M': 'door3'}, 0)

    net = BayesianNet()
    net.add_variable(P)
    net.add_variable(F)
    net.add_variable(M)

    net.add_dependence(M, F)
    net.add_dependence(M, P)

    net.add_prob_table(P, tP)
    net.add_prob_table(F, tF)
    net.add_prob_table(M, tM)

    jtree = JunctionTree([P, F, M])

    jtree.add_clique([P, F, M])

    return net, jtree


def build_chestclinic():
    A = Variable('A', "Visit to Asia?", ['yes', 'no'])
    T = Variable('T', "Tuberculosis?", ['yes', 'no'])
    L = Variable('L', "Lung cancer?", ['yes', 'no'])
    E = Variable('E', "Tuberculosis or cancer?", ['yes', 'no'])
    S = Variable('S', "Smoker?", ['yes', 'no'])
    B = Variable('B', "Bronchitis?", ['yes', 'no'])
    D = Variable('D', "Dyspnoea?", ['yes', 'no'])
    X = Variable('X', "Positive X-ray?", ['yes', 'no'])

    tA = BeliefTable([A])
    tT = BeliefTable([A, T])
    tL = BeliefTable([S, L])
    tE = BeliefTable([E, L, T])
    tS = BeliefTable([S])
    tB = BeliefTable([S, B])
    tD = BeliefTable([E, D, B])
    tX = BeliefTable([E, X])

    # Fill tables
    tA.set_probability_dict({'A': 'yes'}, 0.01)
    tA.set_probability_dict({'A': 'no'}, 0.99)

    tT.set_probability_dict({'A': 'yes', 'T': 'yes'}, 0.05)
    tT.set_probability_dict({'A': 'yes', 'T': 'no'}, 0.95)
    tT.set_probability_dict({'A': 'no', 'T': 'yes'}, 0.01)
    tT.set_probability_dict({'A': 'no', 'T': 'no'}, 0.99)

    tL.set_probability_dict({'S': 'yes', 'L': 'yes'}, 0.1)
    tL.set_probability_dict({'S': 'yes', 'L': 'no'}, 0.9)
    tL.set_probability_dict({'S': 'no', 'L': 'yes'}, 0.01)
    tL.set_probability_dict({'S': 'no', 'L': 'no'}, 0.99)

    tE.set_probability_dict({'T': 'yes', 'L': 'yes', 'E': 'yes'}, 1)
    tE.set_probability_dict({'T': 'yes', 'L': 'yes', 'E': 'no'}, 0)
    tE.set_probability_dict({'T': 'yes', 'L': 'no', 'E': 'yes'}, 1)
    tE.set_probability_dict({'T': 'yes', 'L': 'no', 'E': 'no'}, 0)
    tE.set_probability_dict({'T': 'no', 'L': 'yes', 'E': 'yes'}, 1)
    tE.set_probability_dict({'T': 'no', 'L': 'yes', 'E': 'no'}, 0)
    tE.set_probability_dict({'T': 'no', 'L': 'no', 'E': 'yes'}, 0)
    tE.set_probability_dict({'T': 'no', 'L': 'no', 'E': 'no'}, 1)

    tS.set_probability_dict({'S': 'yes'}, 0.5)
    tS.set_probability_dict({'S': 'no'}, 0.5)

    tB.set_probability_dict({'S': 'yes', 'B': 'yes'}, 0.6)
    tB.set_probability_dict({'S': 'yes', 'B': 'no'}, 0.4)
    tB.set_probability_dict({'S': 'no', 'B': 'yes'}, 0.3)
    tB.set_probability_dict({'S': 'no', 'B': 'no'}, 0.7)

    tD.set_probability_dict({'B': 'yes', 'E': 'yes', 'D': 'yes'}, 0.9)
    tD.set_probability_dict({'B': 'yes', 'E': 'yes', 'D': 'no'}, 0.1)
    tD.set_probability_dict({'B': 'yes', 'E': 'no', 'D': 'yes'}, 0.8)
    tD.set_probability_dict({'B': 'yes', 'E': 'no', 'D': 'no'}, 0.2)
    tD.set_probability_dict({'B': 'no', 'E': 'yes', 'D': 'yes'}, 0.7)
    tD.set_probability_dict({'B': 'no', 'E': 'yes', 'D': 'no'}, 0.3)
    tD.set_probability_dict({'B': 'no', 'E': 'no', 'D': 'yes'}, 0.1)
    tD.set_probability_dict({'B': 'no', 'E': 'no', 'D': 'no'}, 0.9)

    tX.set_probability_dict({'E': 'yes', 'X': 'yes'}, 0.98)
    tX.set_probability_dict({'E': 'yes', 'X': 'no'}, 0.02)
    tX.set_probability_dict({'E': 'no', 'X': 'yes'}, 0.05)
    tX.set_probability_dict({'E': 'no', 'X': 'no'}, 0.95)

    net = BayesianNet()

    net.add_variable(A)
    net.add_variable(T)
    net.add_variable(L)
    net.add_variable(E)
    net.add_variable(S)
    net.add_variable(B)
    net.add_variable(D)
    net.add_variable(X)

    net.add_dependence(T, A)
    net.add_dependence(L, S)
    net.add_dependence(B, S)
    net.add_dependence(E, L)
    net.add_dependence(E, T)
    net.add_dependence(D, E)
    net.add_dependence(D, B)
    net.add_dependence(X, E)

    net.add_prob_table(A, tA)
    net.add_prob_table(T, tT)
    net.add_prob_table(L, tL)
    net.add_prob_table(E, tE)
    net.add_prob_table(S, tS)
    net.add_prob_table(B, tB)
    net.add_prob_table(D, tD)
    net.add_prob_table(X, tX)

    jtree = JunctionTree([A, T, L, E, S, B, D, X])

    jtree.add_clique([A, T])
    jtree.add_clique([E, L, T])
    jtree.add_clique([E, S, L])
    jtree.add_clique([E, B, S])
    jtree.add_clique([E, B, D])
    jtree.add_clique([E, X])


    jtree.connect_cliques([A, T], [E, L, T])
    jtree.connect_cliques([E, S, L], [E, L, T])
    jtree.connect_cliques([E, S, B], [E, L, S])
    jtree.connect_cliques([E, S, B], [E, B, D])
    jtree.connect_cliques([E, B, D], [E, X])



    return net, jtree










